### ISSUE TITLE
获取动态时报错

### ISSUE THREAD

**Issue by Parirose** [SuperGuGuGu/nonebot_plugin_bili_push#15]
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\__init__.py", line 331, in
 run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line
201, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\uvicorn\server.py", line 61, in ru
n
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\apscheduler\executors\base_py3.py"
, line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot_plugin_bili_push\__init__.
py", line 2569, in run_bili_push
    returnjson = connect_api("json", url)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot_plugin_bili_push\__init__.
py", line 27, in connect_api
    return json.loads(httpx.get(url).text)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_api.py", line 189, in get
    return request(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_api.py", line 92, in reques
t
    with Client(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_client.py", line 682, in __
init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[BaseTransport]] = {
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_client.py", line 685, in <d
ictcomp>
    else self._init_proxy_transport(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_client.py", line 739, in _i
nit_proxy_transport
    return HTTPTransport(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_transports\default.py", lin
e 149, in __init__
    self._pool = httpcore.HTTPProxy(
TypeError: HTTPProxy.__init__() got an unexpected keyword argument 'proxy_ssl_context'

**Comment by SuperGuGuGu** [comment]
尝试关闭代理再运行插件

**Comment by Parirose** [comment]
> 尝试关闭代理再运行插件

有效 但其他插件需要代理怎么办？

**Comment by SuperGuGuGu** [comment]
可以参考知乎文章https://zhuanlan.zhihu.com/p/350015032

**Comment by Parirose** [comment]
> 可以参考知乎文章https://zhuanlan.zhihu.com/p/350015032

感谢
