### ISSUE TITLE
sqlite3.OperationalError: no such table: wait_push2

### ISSUE THREAD

**Issue by Todysheep** [SuperGuGuGu/nonebot_plugin_bili_push#18]
```
02-23 14:44:45 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bili_push, lineno=2067) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Python\Lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "C:\Python\Lib\site-packages\nonebot\drivers\fastapi.py", line 185, in run
    uvicorn.run(
  File "C:\Python\Lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Python\Lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Python\Lib\asyncio\base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "C:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python\Lib\asyncio\base_events.py", line 639, in run_forever
    self._run_once()
  File "C:\Python\Lib\asyncio\base_events.py", line 1985, in _run_once
    handle._run()
  File "C:\Python\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Python\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Python\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Python\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Python\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Python\Lib\site-packages\nonebot_plugin_bili_push\__init__.py", line 2361, in bili_push_command
    cursor.execute(f"SELECT * FROM wait_push2 WHERE uid='{uid}'")
sqlite3.OperationalError: no such table: wait_push2
```

**Comment by SuperGuGuGu** [comment]
已更新插件。可以更新插件来解决问题，或者等插件刷新时自动创建数据库。

**Comment by Todysheep** [comment]
好快的更，感谢！
