### ISSUE TITLE
[bug]插件获取不到up主头像与名字

### ISSUE THREAD

**Issue by ElaineOwO** [SuperGuGuGu/nonebot_plugin_bili_push#24]
可以正常推送 但头像与名字为空 
头像显示全黑   名字显示'name"

**Comment by SuperGuGuGu** [comment]
是全部没头像还是部分没头像？没头像的用户是否仅为“没有头像框”？

**Comment by ElaineOwO** [comment]
> 是全部没头像还是部分没头像？没头像的用户是否仅为“没有头像框”？

我也只关注了一个UP的直播推送。。没头像的用户头像就是纯黑的 别的啥都没有  直播间标题和封面都显示正常  

刚刚更新了一下插件 使用 获取最新动态 123456（某UP的uid） 的时候，出现报错勒
```
04-04 22:34:23 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bili_push, lineno=2080) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\BOT\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\BOT\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\BOT\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\BOT\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\BOT\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\BOT\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot_plugin_bili_push\__init__.py", line 2226, in bili_push_command
    draw_info = get_draw(returnjson["data"]["cards"][0])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by SuperGuGuGu** [comment]
这个报错是返回的json有问题，目前修不了 (#23 )

**Comment by SuperGuGuGu** [comment]
头像黑色的话，理论上还能修一下

**Comment by SuperGuGuGu** [comment]
头像问题已尝试修复，请更新到1.1.23查看

**Comment by ElaineOwO** [comment]
> 头像问题已尝试修复，请更新到1.1.23查看

好的，感谢大佬更新。 我先运行一阵子看看
