### ISSUE TITLE
[BUG]调用get_bots()导致Telegram适配器报错

### ISSUE THREAD

**Issue by bywhite0** [SuperGuGuGu/nonebot_plugin_bili_push#7]
log:
```
07-28 12:34:11 [ERROR] apscheduler | Job "run_bili_push (trigger: cron[minute='*/1'], next run at: 2023-07-28 13:35:00 JST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_reboot/reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_bili_push/__init__.py", line 2687, in run_bili_push
    friends = await nonebot.get_bot(botid).get_friend_list()
  File "/usr/local/lib/python3.10/dist-packages/nonebot/adapters/telegram/bot.py", line 105, in call_api
    return await super().call_api(api, **kargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/adapters/telegram/adapter.py", line 237, in _call_api
    raise ApiNotAvailable
nonebot.adapters.telegram.exception.ApiNotAvailable: ApiNotAvailable()
```
若只支持 `OneBot V11` 适配器请加入对连接的 bot 所用适配器的判断，非 `OneBot V11` 适配器则跳过。

edit: 也可以使用 SAA 实现跨平台支持（

**Comment by bywhite0** [comment]
另外你这 API 有点离谱啊，我用的海外服务器 ping 不到，只能改 hosts（

**Comment by SuperGuGuGu** [comment]
感谢指出，在稍后版本将添加对适配器的检测。目前插件仅支持onebot.v11适配器，其余适配器暂无计划支持。
 
另外关于海外服务器无法访问api的问题。由于本人没有充足精力去管理并维护海外区域的访问，因此并没有对海外地区开启api的访问。建议租用大陆地区的服务器。

**Comment by SuperGuGuGu** [comment]
另外关于海外服务器也可以通过国内服务器api的形式进行内容进行转达。具体请查找api搭建相关内容。

**Comment by SuperGuGuGu** [comment]
有需要的话也可以增加这一行配置，将请求换到对应服务器。
bilipush_apiurl="http://cdn.kanon.ink"
