### ISSUE TITLE
[ERROR] apscheduler | Job "run_bili_push (trigger: cron[minute='*/1'], next run at: 2023-09-26 12:50:00 C ST)" raised an exception

### ISSUE THREAD

**Issue by Parirose** [SuperGuGuGu/nonebot_plugin_bili_push#9]
检测动态后报错
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\__init__.py", line 331, in
 run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line
201, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\uvicorn\server.py", line 61, in ru
n
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\apscheduler\executors\base_py3.py"
, line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot_plugin_bili_push\__init__.
py", line 2754, in run_bili_push
    if uid in plugin_config("ignore_live_list", groupcode):
TypeError: argument of type 'NoneType' is not iterable

env配置项如下
#bilipush
bilipush_waittime=1
bilipush_apiurl="http://cdn.kanon.ink"

**Comment by SuperGuGuGu** [comment]
已修复，请更新到最新版本查看（1.0.3）

**Comment by Parirose** [comment]
> 已修复，请更新到最新版本查看（1.0.3）

测试正常 顺便问问at全体现在是不能用吗

**Comment by SuperGuGuGu** [comment]
不能。那段代码不确定可以正常使用。
